server:
  port: 8080
  servlet:
    context-path: /dgut-sports

spring:
  # 关闭jmx资源管理器
  jmx:
    enabled: false

# xml文件映射
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true