server:
  port: 8080
  servlet:
    context-path: /sports
redis:
  host: 172.31.18.22
spring:
  redis:
    lettuce:
      pool:
        max-active: 20000
        #TODO 手动配置:5000
        #TODO 自动配置:5s
        max-wait: 5000
        max-idle: 40
        min-idle: 0
    host: ${redis.host}
    port: 6380
    password: zc@redis.161104
    #TODO 手动配置:3000
    #TODO 自动配置:3s
    timeout: 3000

  # 数据库连接池
  datasource:
    ip: 219.222.189.62
    port: 3306
    database: dgut_sport
    username: root
    password: zc161104
    url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.database}?characterEncoding=utf8&useSSL=false&useUnicode=true&allowMultiQueries=true&autoReconnect=true
    hikari:
      maximum-pool-size: 5000
      minimum-idle: 5
      idle-timeout: 10000
      auto-commit: true
      #pool-name: Hikari_Connection_Pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource

  #  # 缓存
  #  cache:
  #    redis:
  #      cache-null-values: true
  #      time-to-live: 5m

  # 关闭jmx资源管理器
  jmx:
    enabled: false

# xml文件映射
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# SQL打印
logging:
  level:
    com:
      zemcho:
        pe:
          mapper: debug
# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true
