redis:
  host: 172.31.18.22
  timeout: 3000
spring:
  redis:
    lettuce:
      pool:
        max-active: 50000
        #TODO 手动配置:3000
        #TODO 自动配置:3s
        max-wait: 3000
        max-idle: 40
        min-idle: 0
    # 大厅
    ehall:
      host: 219.222.189.156
      port: 6379
      database: 0
      password: klinson
      timeout: ${redis.timeout}
    # 写
    write:
      host: ${redis.host}
      port: 6380
      database: 1
      password: zc@redis.161104
      timeout: ${redis.timeout}
    # 读
    read:
      host: ${redis.host}
      port: 6381
      database: 1
      password: zc@redis.161104
      timeout: ${redis.timeout}

  # 数据库连接池
  datasource:
    ip: 219.222.189.62
    port: 3306
    database: dgut_sport
    username: root
    password: zc161104
    url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.database}?characterEncoding=utf8&useSSL=false&useUnicode=true&allowMultiQueries=true&autoReconnect=true
    hikari:
      maximum-pool-size: 5000
      minimum-idle: 5
      idle-timeout: 10000
      auto-commit: true
      #pool-name: Hikari_Connection_Pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource